//
//  Localize.swift
//  tiX
//
//  Created by Nicolas Ott on 02.06.21.
//

import SwiftUI

let loc_all: LocalizedStringKey = "loc_all"
let loc_name: LocalizedStringKey = "loc_name"
let loc_welcome: LocalizedStringKey = "loc_welcome"
let loc_tix: LocalizedStringKey = "loc_tix"
let loc_how: LocalizedStringKey = "loc_how"
let loc_today: LocalizedStringKey = "loc_today"
let loc_overdue: LocalizedStringKey = "loc_overdue"
let loc_open_tasks: LocalizedStringKey = "loc_open_tasks"
let loc_todo: LocalizedStringKey = "loc_todo"
let loc_todos: LocalizedStringKey = "loc_todos"
let loc_all_todos: LocalizedStringKey = "loc_all_todos"
let loc_category: LocalizedStringKey = "loc_category"
let loc_categories: LocalizedStringKey = "loc_categories"
let loc_new_todo: LocalizedStringKey = "loc_new_todo"
let loc_new_cat: LocalizedStringKey = "loc_new_cat"
let loc_choose_category: LocalizedStringKey = "loc_choose_category"
let loc_duedate: LocalizedStringKey = "loc_duedate"
let loc_important: LocalizedStringKey = "loc_important"
let loc_save: LocalizedStringKey = "loc_save"
let loc_discard: LocalizedStringKey = "loc_discard"
let loc_set_duedate: LocalizedStringKey = "loc_set_duedate"
let loc_settings: LocalizedStringKey = "loc_settings"
let loc_hide_ticked: LocalizedStringKey = "loc_hide_ticked"
let loc_delete_ticked: LocalizedStringKey = "loc_delete_ticked"
let loc_help: LocalizedStringKey = "loc_help"
let loc_feedback: LocalizedStringKey = "loc_feedback"
let loc_support: LocalizedStringKey = "loc_support"
let loc_contact: LocalizedStringKey = "loc_contact"
let loc_about: LocalizedStringKey = "loc_about"
let loc_madewithlove: LocalizedStringKey = "loc_madewithlove"
let loc_color: LocalizedStringKey = "loc_color"
let loc_select_color: LocalizedStringKey = "loc_select_color"
let loc_dashboard: LocalizedStringKey = "loc_dashboard"
let loc_your_todos: LocalizedStringKey = "loc_your_todos"
let loc_delete: LocalizedStringKey = "loc_delete"
let loc_go: LocalizedStringKey = "loc_go"
let loc_default_cat: LocalizedStringKey = "loc_default_cat"
let loc_no_todos: LocalizedStringKey = "loc_no_todos"
let loc_app_version: LocalizedStringKey = "loc_app_version"
let loc_deleted: LocalizedStringKey = "loc_deleted"
let loc_gdpr: LocalizedStringKey = "loc_gdpr"
let loc_gdpr_header: LocalizedStringKey = "loc_gdpr_header"
let loc_gdpr_subheader: LocalizedStringKey = "loc_gdpr_subheader"
let loc_gdpr_lastupdated: LocalizedStringKey = "loc_gdpr_lastupdated"
let loc_gdpr_text: LocalizedStringKey = "loc_gdpr_text"
let loc_rn: LocalizedStringKey = "loc_rn"
let loc_whatsnew: LocalizedStringKey = "loc_whatsnew"
let loc_theme: LocalizedStringKey = "loc_theme"
let loc_ok: LocalizedStringKey = "loc_ok"
